### ISSUE TITLE
YouTube - User's Specific Playlist

### ISSUE THREAD

**Issue by SlickRemix** [SlickRemix/feed-them-social#172]

**Comment by slickchris** [comment]
Ch808 test for "YouTube - User's Specific Playlist" using some Keto recipe playlist I found the appropriate URL for. (again, YT is switching to URL 'handles' and finding the old URLs is difficult, but I found one). *same issue with large video slot. Nothing/error message shows, but clicking on any of the smaller videos will play that video in the large video slot.

ch808 frontend test page link: [https://ch808shoots.com/y-4-0-yt-users-specific-playlist/](url)

ch808 backend test page link: [https://ch808shoots.com/wp-admin/post.php?post=1288&action=edit&classic-editor=1](url)

ch808 FT Settings backend page link: [https://ch808shoots.com/wp-admin/post.php?post=1362&action=edit#youtube_feed](url)
