### ISSUE TITLE
YouTube - Single Video with title, date & description

### ISSUE THREAD

**Issue by SlickRemix** [SlickRemix/feed-them-social#173]

**Comment by slickchris** [comment]
ch808 test for "YouTube - Single Video with title, date & description" using the most recent video from Peter McKinnon.

ch808 frontend page link: [https://ch808shoots.com/y-4-0-yt-single-video-w-title-date-description/](url)

ch808 backend page link: [https://ch808shoots.com/wp-admin/post.php?post=1290&action=edit&classic-editor=1](url)

ch808 FT Settings backend page link: [https://ch808shoots.com/wp-admin/post.php?post=1553&action=edit#youtube_feed](url)

**Comment by slickchris** [comment]
While this test, "YouTube - Single Video with title, date & description" went fine, Adding New Feed and getting YT access token seems really hit & miss with the loop redirect. It took me 3 tries to get the API Key token to stick. ugh! that loop. Obviously, I eventually got it.
