### ISSUE TITLE
Facebook - Albums

### ISSUE THREAD

**Issue by SlickRemix** [SlickRemix/feed-them-social#175]

**Comment by slickchris** [comment]
FB "Album Covers" test. Using ch808 site & SlickRemix FB Album Covers as test.

ch808 frontend page link: [https://ch808shoots.com/w-4-0-fb-album-covers-test/](url)

ch808 backend page link: [https://ch808shoots.com/wp-admin/post.php?post=1491&action=edit&classic-editor=1](url)

ch808 FT Social settings backend link: [https://ch808shoots.com/wp-admin/post.php?post=1494&action=edit#facebook_feed](url)
