### ISSUE TITLE
Facebook - Page

### ISSUE THREAD

**Issue by SlickRemix** [SlickRemix/feed-them-social#177]

**Comment by slickchris** [comment]
Facebook Main Page.

ch808 frontend link: [https://ch808shoots.com/z-4-0-fb-feed/](url)

ch808 backend link: [https://ch808shoots.com/wp-admin/post.php?post=1253&action=edit](url)

ch808 FT Social settings backend link: [https://ch808shoots.com/wp-admin/post.php?post=1298&action=edit&classic-editor=1#facebook_feed](url)
