### ISSUE TITLE
Facebook - Reviews

### ISSUE THREAD

**Issue by SlickRemix** [SlickRemix/feed-them-social#178]

**Comment by slickchris** [comment]
ch808 test of "FB - Reviews" using SlickRemix FB Page reviews on ch808shoots site.

ch808 frontend page link: [https://ch808shoots.com/ww-4-0-fb-reviews/](url)

ch808 backend page link: [https://ch808shoots.com/wp-admin/post.php?post=1274&action=edit](url)

ch808 FT Settings backend link: [https://ch808shoots.com/wp-admin/post.php?post=1323&action=edit&classic-editor=1#facebook_feed](url)

**Comment by justinslickremix** [comment]
@spencerslickremix 
Load more on frontend and Backend is just duplicating reviews. 

![Image](https://user-images.githubusercontent.com/50183104/219111280-9470ce38-bdf2-4913-936d-be0b7198a4a4.png)

**Comment by justinslickremix** [comment]
@spencer Fixed with DC version update!
