### ISSUE TITLE
Facebook - Carousel  - Albums

### ISSUE THREAD

**Issue by SlickRemix** [SlickRemix/feed-them-social#180]

**Comment by slickchris** [comment]
ch808 test "FB - Carousel - Album Covers" test. Using BBM album covers on ch808shoots site.

ch808 frontend page link: [https://ch808shoots.com/ww-fb-carousel-albums/](url)

ch808 backend page link: [https://ch808shoots.com/wp-admin/post.php?post=1506&action=edit&classic-editor=1](url)

ch808 FT Settings backend page link: [https://ch808shoots.com/wp-admin/post.php?post=1509&action=edit#facebook_feed](url)

**Comment by justinslickremix** [comment]
@spencerslickremix not sure why but some images are not loading beyond first 3 here.
![Image](https://user-images.githubusercontent.com/50183104/219112360-3cd29d77-b657-41d8-ad52-d58b9ff46b02.png)

**Comment by SlickRemix** [comment]
@SlickRemix @justinslickremix those are albums you can remove if they have no cover photo. 

![Image](https://user-images.githubusercontent.com/10436193/219869892-8d125274-1feb-454b-8a2a-c77df16d4a8e.png)
