### ISSUE TITLE
Facebook - Carousel  - Albums Photos

### ISSUE THREAD

**Issue by SlickRemix** [SlickRemix/feed-them-social#181]

**Comment by slickchris** [comment]
Two FB Album Phots Carousel feeds. Same site. Same settings. Different results. CH808 is janky. BBM seems fine.

[https://ch808shoots.com/ww-4-0-fb-carousel-album-photos/](https://github.com/users/SlickRemix/projects/1/views/url)

[https://ch808shoots.com/ww-4-0-carousel-bbm/?preview_id=1339&preview_nonce=f095748ee2&preview=true](https://github.com/users/SlickRemix/projects/1/views/url)
