### ISSUE TITLE
Facebook - Carousel  - Videos

### ISSUE THREAD

**Issue by SlickRemix** [SlickRemix/feed-them-social#182]

**Comment by slickchris** [comment]
ch808shoots test for "FB - Carousel - Videos" using BBM videos on ch808shoots site.

ch808 frontend page link: [https://ch808shoots.com/ww-4-0-fb-carousel-videos/](url)

ch808 backend page link: [https://ch808shoots.com/wp-admin/post.php?post=1278&action=edit&classic-editor=1](url)

ch808 FT Settings backend link: [https://ch808shoots.com/wp-admin/post.php?post=1518&action=edit#facebook_feed](url)
