### ISSUE TITLE
Instagram - Basic

### ISSUE THREAD

**Issue by SlickRemix** [SlickRemix/feed-them-social#183]

**Comment by slickchris** [comment]
CH808 Instagram Basic test.

Ch808 frontend link: [https://ch808shoots.com/z-4-0-instagram-basic/](url)

ch808 backend page link: [https://ch808shoots.com/wp-admin/post.php?post=1255&action=edit](url)

ch808 FT Social backend settings link: [https://ch808shoots.com/wp-admin/post.php?post=1383&action=edit&classic-editor=1#instagram_feed](url)

**Comment by slickchris** [comment]
Error on ch808 backend page when updating in Classic Editor:


![Image](https://user-images.githubusercontent.com/57366009/215817723-5a0a72a7-40b2-403f-80c8-1580bcbef247.png)

**Comment by justinslickremix** [comment]
@spencerslickremix Checked all links and also checked share options. Linked in getting a broken image but every other one was working perfect.
