### ISSUE TITLE
Instagram - Business

### ISSUE THREAD

**Issue by SlickRemix** [SlickRemix/feed-them-social#184]

**Comment by slickchris** [comment]
Ch808 IG Business feed test.

ch808 frontend link: [https://ch808shoots.com/z-4-0-instagram-biz/](url)

ch808 backend link: [https://ch808shoots.com/wp-admin/post.php?post=1257&action=edit](url)

ch808 FT Social backend settings link: [https://ch808shoots.com/wp-admin/post.php?post=1237&action=edit&classic-editor=1#instagram_feed](url)
