### ISSUE TITLE
Instagram - Business Hashtag

### ISSUE THREAD

**Issue by SlickRemix** [SlickRemix/feed-them-social#185]

**Comment by slickchris** [comment]
ch808 IG Biz Hashtag test. (Hashtag used: moodygrams)

ch808 frontend link: [https://ch808shoots.com/x-4-0-ig-biz-hashtag/](url)

ch808 backend link: [https://ch808shoots.com/wp-admin/post.php?post=1280&action=edit](url)

ch808 FT Social settings backend link: [https://ch808shoots.com/wp-admin/post.php?post=1395&action=edit&classic-editor=1#instagram_feed](url)

**Comment by slickchris** [comment]
Again, in Classic Editor, when updating page, error saving message occurs. Also again, it doesn't seem to effect the frontend page...



![Image](https://user-images.githubusercontent.com/57366009/215820704-6c33b42c-dbf1-4174-9ec2-fe88df084ed8.png)
