### ISSUE TITLE
Twitter - User

### ISSUE THREAD

**Issue by SlickRemix** [SlickRemix/feed-them-social#186]

**Comment by slickchris** [comment]
Ch808 Twitter user test: Using NatGeo account as test (*many images & videos not showing... only one of each, screenshot in next comment)

Ch808 frontend link: [https://ch808shoots.com/z-4-0-twitter-feed/](url)

Ch808 backend page link: [https://ch808shoots.com/wp-admin/post.php?post=1259&action=edit](url)

Ch808 FT Social settings backend link: [https://ch808shoots.com/wp-admin/post.php?post=1403&action=edit&classic-editor=1#twitter_feed](url)

**Comment by slickchris** [comment]
frontend missing images/videos:



![Image](https://user-images.githubusercontent.com/57366009/215826615-63cf2d00-ff2b-471f-b141-4aefb464ff0d.png)

**Comment by justinslickremix** [comment]
![Image](https://user-images.githubusercontent.com/50183104/219107719-c983a1f7-fea5-43e2-a625-288bfea852aa.png)

I have found is backend link not showing example feed properly.

**Comment by SlickRemix** [comment]
@justinslickremix ah looks like I need to add the grid refresh js on direct page load. It also appears something is missing on 4.0 where the shared link image and text are not appearing like here. https://feedthemsocial.com/twitter-feed-demo/?feedID=NatGeo cc: @slickchris

**Comment by SlickRemix** [comment]
@justinslickremix @slickchris the shared link images etc are showing up now.

![Image](https://user-images.githubusercontent.com/10436193/219777292-cfd0604d-a341-465b-9adf-a50cac381e53.png)
