### ISSUE TITLE
Twitter - Hashtag & Search

### ISSUE THREAD

**Issue by SlickRemix** [SlickRemix/feed-them-social#187]

**Comment by slickchris** [comment]
ch808 test for "Twitter - Hashtag & Search" using the hashtag #covidisnotover on ch808shoots page.

ch808 frontend page link: [https://ch808shoots.com/z-4-0-twitter-hashtag-search/](url)

ch808 backend page link: [https://ch808shoots.com/wp-admin/post.php?post=1282&action=edit](url)

ch808 FT Social settings backend page link: [https://ch808shoots.com/wp-admin/post.php?post=1413&action=edit&classic-editor=1#twitter_feed](url)

**Comment by justinslickremix** [comment]
@spencerslickremix Definitely a div/wrapper missing or something on twitter feed backend example feed. Frontend looks fine.

![Image](https://user-images.githubusercontent.com/50183104/219115774-5f7cafd1-06f6-4524-8b30-952c10d306b4.png)
