### ISSUE TITLE
YouTube - Channel

### ISSUE THREAD

**Issue by SlickRemix** [SlickRemix/feed-them-social#188]

**Comment by slickchris** [comment]
ch808 YouTube Channel test (Using Big Bolt Media YT page/channel)

ch808 YT Channel frontend link: [https://ch808shoots.com/z-4-0-youtube-feed/](url)

ch808 backend page link: [https://ch808shoots.com/wp-admin/post.php?post=1261&action=edit](url)

ch808 FT Social settings backend link: [https://ch808shoots.com/wp-admin/post.php?post=1349&action=edit#youtube_feed](url)

**Comment by slickchris** [comment]
ch808 backend error saving message. Again, not affecting the frontend. I suspect that whatever is causing this message in the Classic Editor is the same thing that's causing it in the block editor. Anyway, two screenshots, one of each example (Classic & Block). This is the last time I'll post this in Git, as I assume it'll just keep happening with each feed.



![Image](https://user-images.githubusercontent.com/57366009/215823723-39850f54-d333-4344-9063-b2e246ca4104.png)
![Image](https://user-images.githubusercontent.com/57366009/215823724-3008c22c-f59f-4878-86f3-f8eeef81b56f.png)

**Comment by justinslickremix** [comment]
@spencerslickremix 
Getting weird error on frontend page

![Image](https://user-images.githubusercontent.com/50183104/219108418-efb7282d-5c9c-45d9-86b2-c89ecb5cb99d.png)

**Comment by justinslickremix** [comment]
@spencerslickremix 
Ignore! Just needed to get YouTube access token. We could make a more human readable error message for that for sure.
