### ISSUE TITLE
YouTube - Channel's Specific Playlist

### ISSUE THREAD

**Issue by SlickRemix** [SlickRemix/feed-them-social#189]

**Comment by slickchris** [comment]
ch808 test for "YouTube - Channel's Specific Playlist" using BBM YT playlist on ch808shoots site.

ch808 frontend page link: [https://ch808shoots.com/y-4-0-yt-channel-specific-playlist/](url)

ch808 backend page link: [https://ch808shoots.com/wp-admin/post.php?post=1284&action=edit&classic-editor=1](url)

ch808 FT Settings backend page link: [https://ch808shoots.com/wp-admin/post.php?post=1530&action=edit#youtube_feed](url)
