### ISSUE TITLE
Twitter feed follow option in the header picture is not shown properly

### ISSUE THREAD

**Issue by WebmasterMM** [SlickRemix/feed-them-social#195]
In the Twitter feed in the google browser the follow button is not shown in the widget
![Schermafbeelding 2023-02-23 193941](https://user-images.githubusercontent.com/126196021/221000957-22bc2a76-5914-4666-b50f-9ff7a77712c9.png)
 while it is turned on

**Comment by spencerslickremix** [comment]
Thanks for reporting. This should be fixed in our latest version. Let me know if that helps.
