### ISSUE TITLE
Error with disconnected Facebook

### ISSUE THREAD

**Issue by LiamMcArthur** [SlickRemix/feed-them-social#237]
I'm currently working on a website which had a Facebook feed integration but the integration has since expired and we need to reconnect it. This is causing an error to be thrown every time we attempt to save data using Elementor:

`2023/06/28 13:08:44 [error] 4235#4235: *8905 FastCGI sent in stderr: "PHP message: PHP Warning:  Invalid argument supplied for foreach() in /home/***/www.************.com/wp-content/plugins/feed-them-social/includes/feeds/facebook/class-facebook-feed.php on line 1448PHP message: PHP Warning:  Invalid argument supplied for foreach() in /home/***/www.************.com/wp-content/plugins/feed-them-social/includes/feeds/facebook/class-facebook-feed.php on line 919PHP message: PHP Warning:  Invalid argument supplied for foreach() in /home/***/www.************.com/wp-content/plugins/feed-them-social/includes/feeds/facebook/class-facebook-feed.php on line 930" while reading response header from upstream, client: 86.188.212.228, server: www.************.com, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm-***.sock:", host: "www.************.com", referrer: "https://www.************.com/************/?elementor-preview=577&ver=1687957623`

I believe the reason for this is that it then attempts to loop over feed data which doesn't exist.

**Comment by spencerslickremix** [comment]
Thanks for the heads-up and the code edit. Can you confirm the feed still works after re-connecting it along with your edit?

**Comment by spencerslickremix** [comment]
I'm also curious to know if you had debug mode set to true as well while making your changes with Elementor?

**Comment by LiamMcArthur** [comment]
It looks like we're still getting a few other errors in that same file which I've accounted for in the PR. I haven't yet been able to re-connect the Facebook account but I should have the credentials tomorrow so will be able to test thoroughly. Nope, debug bar wasn't enabled at the time.

**Comment by LiamMcArthur** [comment]
@spencerslickremix I should have these over today so that I can test the above.

**Comment by LiamMcArthur** [comment]
@spencerslickremix tested these changes in a production environment and it seems to be working fine without errors.

**Comment by SlickRemix** [comment]
@LiamMcArthur Excellent, thanks for helping us out here. I'll review these and most likely add them to a push we have scheduled early next week.
